# Generated by Django 5.1.3 on 2024-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_optimize_active',
            field=models.BooleanField(default=False, verbose_name='最適化アクティブ'),
        ),
    ]
