# Generated by Django 5.1.3 on 2024-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_optimize_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('base_user', '基本ユーザー'), ('custom_user', 'カスタムユーザー'), ('cafe_staff', 'カフェスタッフ')], default=None, max_length=20, null=True),
        ),
    ]
