# Generated by Django 5.1.3 on 2024-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_baseuser_gender_baseuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('master_user', 'マスターユーザー'), ('custom_user', 'カスタムユーザー'), ('staff_user', 'カフェスタッフ')], default=None, max_length=20, null=True),
        ),
    ]
