# Generated by Django 5.1.3 on 2024-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamecafe',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='match_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
