# Generated by Django 5.1.3 on 2024-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_boardgamecafe_capacity_boardgamecafe_match_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgamecafe',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='boardgamecafe',
            name='match_capacity',
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='closing_time',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='opening_time',
            field=models.TimeField(default='13:00'),
        ),
    ]
