# Generated by Django 5.1.3 on 2025-02-18 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_boardgamecafe_friday_close_boardgamecafe_friday_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('light', '軽量級'), ('medium', '中量級'), ('heavy', '重量級')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boardgame',
            name='board_image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgame_images/board/'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='box_image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgame_images/box/'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardgame',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(default=1, help_text='最大人数'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='max_playtime',
            field=models.IntegerField(blank=True, help_text='最長プレイ時間 (分)', null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(default=1, help_text='最小人数'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='min_playtime',
            field=models.IntegerField(blank=True, help_text='最短プレイ時間 (分)', null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='designers',
            field=models.ManyToManyField(related_name='boardgames', to='accounts.designer'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='game_categories',
            field=models.ManyToManyField(related_name='boardgames', to='accounts.gamecategory'),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='game_mechanics',
            field=models.ManyToManyField(related_name='boardgames', to='accounts.gamemechanic'),
        ),
    ]
