# Generated by Django 5.1.3 on 2025-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_boardgame_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
