# Generated by Django 5.1.3 on 2025-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_gamecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='designers',
            field=models.ManyToManyField(blank=True, related_name='boardgames', to='accounts.designer'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='game_categories',
            field=models.ManyToManyField(blank=True, related_name='boardgames', to='accounts.gamecategory'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='game_mechanics',
            field=models.ManyToManyField(blank=True, related_name='boardgames', to='accounts.gamemechanic'),
        ),
    ]
