# Generated by Django 5.1.3 on 2025-02-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_boardgame_designers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='walking_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgamecafe',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='boardgamecafe',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.prefecture'),
        ),
    ]
