# Generated by Django 5.1.3 on 2025-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_prefecture_boardgamecafe_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamecafe',
            name='walking_minutes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
