# Generated by Django 5.1.3 on 2025-02-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_boardgamecafe_walking_minutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameMechanic',
            new_name='GameTag',
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='game_mechanics',
            new_name='game_tags',
        ),
    ]
