# Generated by Django 5.1.3 on 2025-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_gamemechanic_gametag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCategory',
            new_name='GameClass',
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='game_categories',
            new_name='game_class',
        ),
    ]
