# Generated by Django 4.2.16 on 2024-10-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_install', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cafestaff')),
            ],
        ),
    ]
