# Generated by Django 5.1.3 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_message_related_suggest_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestgameinstructor',
            name='is_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
