# Generated by Django 4.2.16 on 2024-10-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cafes', '0003_alter_cafegamerelation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffgamerelation',
            unique_together={('staff', 'game')},
        ),
    ]
