# Generated by Django 5.1.3 on 2025-03-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_suggestgameinstructor_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestgame',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
