# Generated by Django 4.2.16 on 2024-10-20 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cafes', '0006_rename_can_install_cafegamerelation_can_instruct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafegamerelation',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_relations', to='accounts.boardgamecafe'),
        ),
        migrations.AlterField(
            model_name='cafegamerelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_relations', to='accounts.boardgame'),
        ),
        migrations.AlterField(
            model_name='staffgamerelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_relations', to='accounts.boardgame'),
        ),
        migrations.AlterField(
            model_name='staffgamerelation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_relations', to='accounts.cafestaff'),
        ),
    ]
