# Generated by Django 5.1.3 on 2024-12-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_boardgamecafe_capacity_boardgamecafe_match_capacity'),
        ('cafes', '0007_alter_cafegamerelation_cafe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_relations', to='accounts.boardgamecafe')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservatin_relations', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_type', models.CharField(choices=[('matched', 'マッチング予約'), ('direct', '直接予約'), ('phone', '電話予約')], default='direct', max_length=20)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgamecafe')),
                ('participant', models.ManyToManyField(through='cafes.Participant', to='accounts.customuser')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.cafetable')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='cafes.reservation'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_relations', to='cafes.cafetable')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_relations', to='cafes.reservation')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservatin_relations', to='cafes.timeslot')),
            ],
            options={
                'unique_together': {('reservation', 'timeslot')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ManyToManyField(through='cafes.ReservationTimeSlot', to='cafes.timeslot'),
        ),
    ]
