# Generated by Django 5.1.3 on 2024-12-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_timeslot_is_closing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='is_closing',
            new_name='is_closed',
        ),
    ]
