# Generated by Django 5.1.3 on 2024-12-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_rename_is_closing_timeslot_is_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CafeOperatingHours',
        ),
    ]
