# Generated by Django 5.1.3 on 2024-12-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_delete_cafeoperatinghours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlot',
            new_name='TableTimeSlot',
        ),
    ]
