# Generated by Django 5.1.3 on 2025-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_alter_tabletimeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='count',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
