# Generated by Django 5.1.3 on 2025-02-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0017_remove_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='game_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gameclass'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_recruiting',
            field=models.BooleanField(default=False),
        ),
    ]
