# Generated by Django 5.1.3 on 2025-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0018_reservation_game_class_reservation_is_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='choice_game',
            field=models.ManyToManyField(blank=True, related_name='choice_game_reservations', to='accounts.boardgame'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='max_participants',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='play_game',
            field=models.ManyToManyField(blank=True, related_name='play_game_reservations', to='accounts.boardgame'),
        ),
    ]
