# Generated by Django 5.1.3 on 2025-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0019_reservation_choice_game_reservation_max_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='play_game',
        ),
        migrations.AddField(
            model_name='reservation',
            name='play_game_by_user',
            field=models.ManyToManyField(blank=True, related_name='play_game_by_user_reservations', to='accounts.boardgame'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='play_game_in_cafe',
            field=models.ManyToManyField(blank=True, related_name='play_game_in_cafe_reservations', to='accounts.boardgame'),
        ),
    ]
