# Generated by Django 5.1.3 on 2025-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0021_remove_reservation_play_game_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='count',
            field=models.IntegerField(default=4),
        ),
    ]
