# Generated by Django 5.1.3 on 2025-03-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0022_alter_reservation_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_deleted',
            new_name='is_proposal',
        ),
        migrations.AddField(
            model_name='message',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='direct_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GameProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.message')),
                ('participants', models.ManyToManyField(related_name='game_proposals', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='GameProposalInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('game_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.gameproposal')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameproposal',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='explained_game_proposals', through='cafes.GameProposalInstructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
