# Generated by Django 5.1.3 on 2025-03-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0023_rename_is_deleted_message_is_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameproposalinstructor',
            name='game_proposal',
        ),
        migrations.RemoveField(
            model_name='gameproposalinstructor',
            name='instructor',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_proposal',
            new_name='is_suggest',
        ),
        migrations.AddField(
            model_name='message',
            name='is_rule_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GameSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.message')),
                ('participants', models.ManyToManyField(related_name='game_suggests', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='GameSuggestInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suggest_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.gamesuggest')),
            ],
        ),
        migrations.AddField(
            model_name='gamesuggest',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='explained_game_suggests', through='cafes.GameSuggestInstructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GameProposal',
        ),
        migrations.DeleteModel(
            name='GameProposalInstructor',
        ),
    ]
