# Generated by Django 5.1.3 on 2025-03-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('cafes', '0024_remove_gameproposalinstructor_game_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSuggestInstructor',
            new_name='SuggestGameInstructor',
        ),
        migrations.CreateModel(
            name='SuggestGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructors', models.ManyToManyField(blank=True, related_name='explained_suggest_games', through='cafes.SuggestGameInstructor', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.message')),
                ('participants', models.ManyToManyField(related_name='suggest_games', to='accounts.customuser')),
                ('suggest_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
            ],
        ),
        migrations.AlterField(
            model_name='suggestgameinstructor',
            name='suggest_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.suggestgame'),
        ),
        migrations.DeleteModel(
            name='GameSuggest',
        ),
    ]
