# Generated by Django 5.1.3 on 2025-03-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0025_rename_gamesuggestinstructor_suggestgameinstructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
    ]
