# Generated by Django 4.2.16 on 2024-10-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(null=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgamecafe')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('may_follow', models.BooleanField(default=False)),
                ('must_follow', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.customuser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_install', models.BooleanField(default=False)),
                ('want_to_play', models.BooleanField(default=False)),
                ('not_for_me', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserFreeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='月')),
                ('tuesday', models.BooleanField(default=False, verbose_name='火')),
                ('wednesday', models.BooleanField(default=False, verbose_name='水')),
                ('thursday', models.BooleanField(default=False, verbose_name='木')),
                ('friday', models.BooleanField(default=False, verbose_name='金')),
                ('saturday', models.BooleanField(default=False, verbose_name='土')),
                ('sunday', models.BooleanField(default=False, verbose_name='日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserCafeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_visit', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.boardgamecafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matchday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='user',
            field=models.ManyToManyField(through='match.MatchDayUser', to='accounts.customuser'),
        ),
    ]
