# Generated by Django 4.2.16 on 2024-10-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamerelation',
            unique_together={('user', 'game', 'can_install'), ('user', 'game', 'want_to_play'), ('user', 'game', 'not_for_me')},
        ),
    ]
