# Generated by Django 4.2.16 on 2024-10-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('match', '0002_alter_usergamerelation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamerelation',
            unique_together={('user', 'game', 'can_install', 'want_to_play', 'not_for_me')},
        ),
    ]
