# Generated by Django 4.2.16 on 2024-10-20 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('match', '0004_rename_can_install_usergamerelation_can_instruct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamerelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='accounts.boardgame'),
        ),
        migrations.AlterField(
            model_name='usergamerelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_relations', to='accounts.customuser'),
        ),
    ]
