# Generated by Django 4.2.16 on 2024-10-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('match', '0005_alter_usergamerelation_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_to_matchday', to='accounts.boardgame'),
        ),
        migrations.AlterField(
            model_name='matchdayuser',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='match.matchday'),
        ),
        migrations.AlterField(
            model_name='matchdayuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_relations', to='accounts.customuser'),
        ),
        migrations.CreateModel(
            name='GameCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_relations', to='accounts.boardgame')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_relations', to='match.matchday')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='candidate',
            field=models.ManyToManyField(related_name='candidate_to_matchday', through='match.GameCandidate', to='accounts.boardgame'),
        ),
    ]
