# Generated by Django 4.2.16 on 2024-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('match', '0006_alter_matchday_game_alter_matchdayuser_matchday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCandidate',
            new_name='GameChoice',
        ),
        migrations.RemoveField(
            model_name='matchday',
            name='candidate',
        ),
        migrations.AddField(
            model_name='matchday',
            name='choice',
            field=models.ManyToManyField(related_name='choice_to_matchday', through='match.GameChoice', to='accounts.boardgame'),
        ),
    ]
