# Generated by Django 4.0.2 on 2024-11-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_groups_and_more'),
        ('match', '0007_rename_gamecandidate_gamechoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='choice',
            field=models.ManyToManyField(related_name='choice_to_matchday', through='match.GameChoice', to='accounts.BoardGame'),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='user',
            field=models.ManyToManyField(through='match.MatchDayUser', to='accounts.CustomUser'),
        ),
    ]
