# Generated by Django 5.1.3 on 2024-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_alter_matchday_choice_alter_matchday_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfreetime',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='userfreetime',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='friday_daytime',
            field=models.BooleanField(default=False, verbose_name='金昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='friday_nighttime',
            field=models.BooleanField(default=False, verbose_name='金夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='monday_daytime',
            field=models.BooleanField(default=False, verbose_name='月昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='monday_nighttime',
            field=models.BooleanField(default=False, verbose_name='月夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='saturday_daytime',
            field=models.BooleanField(default=False, verbose_name='土昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='saturday_nighttime',
            field=models.BooleanField(default=False, verbose_name='土夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='sunday_daytime',
            field=models.BooleanField(default=False, verbose_name='日昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='sunday_nighttime',
            field=models.BooleanField(default=False, verbose_name='日夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='thursday_daytime',
            field=models.BooleanField(default=False, verbose_name='木昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='thursday_nighttime',
            field=models.BooleanField(default=False, verbose_name='木夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='tuesday_daytime',
            field=models.BooleanField(default=False, verbose_name='火昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='tuesday_nighttime',
            field=models.BooleanField(default=False, verbose_name='火夜'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='wednesday_daytime',
            field=models.BooleanField(default=False, verbose_name='水昼'),
        ),
        migrations.AddField(
            model_name='userfreetime',
            name='wednesday_nighttime',
            field=models.BooleanField(default=False, verbose_name='水夜'),
        ),
    ]
