# Generated by Django 5.1.3 on 2025-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_remove_userfreetime_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
