# Generated by Django 5.1.3 on 2025-02-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('match', '0010_userrelation_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeday', models.DateField()),
                ('daytime', models.BooleanField(default=False, verbose_name='昼')),
                ('nighttime', models.BooleanField(default=False, verbose_name='夜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
