# Generated by Django 5.1.3 on 2025-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_game_class_customuser_prefecture_and_more'),
        ('match', '0011_userfreeday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamerelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergamerelation',
            name='is_having',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='usergamerelation',
            unique_together={('user', 'game', 'can_instruct', 'want_to_play', 'not_for_me', 'is_having')},
        ),
    ]
